export const SETNAMEDATE = 'SETNAMEDATE';
export const SETEMAILDATE = 'SETEMAILDATE';
export const SETTIMEDATE = 'SETTIMEDATE';
export const SETIDDATE = 'SETIDDATE';
export const SETCONFIRMSELECTDATESCREEN = 'CONFIRMSELECTDATESCREEN';
export const NODATA = 'NODATA';

export const NEWDATE = 'NEWDATE';
export const DELDATE = 'DELDATE';
export const EDITDATE = 'EDITDATE';
